spring:
  application:
    name: toto-pizza
  datasource:
    generate-unique-name: false
    name: toto-pizza
    url: jdbc:h2:mem:toto-pizza
    driver-class-name: org.h2.Driver
    username: user
    password: 12345
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG